#!/usr/bin/env node

// For dev only.
// require("babel-register");

// Overrides.
const managerConfig = require("eslint-myrules-manager/lib/config");

managerConfig.pkgConfigName = "novivia-linter";
managerConfig.configFilename = ".novivialinterrc";

const execute = require("eslint-myrules-manager").execute;
const myRules = require("./");

execute(myRules, process.argv);
